// colors.ts

export const COLORS = {
  // === BASE PASTEL ===
  PASTEL_RED: '#F28B82',
  PASTEL_ORANGE: '#FBCB8B',
  PASTEL_YELLOW: '#FFF2A1',
  PASTEL_GREEN: '#B5EAD7',
  PASTEL_BLUE: '#A7C7E7',
  PASTEL_PURPLE: '#CBAACB',
  PASTEL_PINK: '#FFD1DC',
  PASTEL_BROWN: '#E6CBA8',
  PASTEL_GRAY: '#E0E0E0',
  PASTEL_WHITE: '#FAFAFA',

  // === HOVER ===
  PASTEL_RED_HOVER: '#E0746B',
  PASTEL_ORANGE_HOVER: '#F0B873',
  PASTEL_YELLOW_HOVER: '#E8D98D',
  PASTEL_GREEN_HOVER: '#9FD1BE',
  PASTEL_BLUE_HOVER: '#8FAFD0',
  PASTEL_PURPLE_HOVER: '#B092B0',
  PASTEL_PINK_HOVER: '#E6B8C3',
  PASTEL_BROWN_HOVER: '#CCB08E',
  PASTEL_GRAY_HOVER: '#C7C7C7',
  PASTEL_WHITE_HOVER: '#E1E1E1',

  // === FOCUS ===
  PASTEL_RED_FOCUS: '#F5A29A',
  PASTEL_ORANGE_FOCUS: '#FCD7A1',
  PASTEL_YELLOW_FOCUS: '#FFF6B8',
  PASTEL_GREEN_FOCUS: '#C9F0E1',
  PASTEL_BLUE_FOCUS: '#BAD4ED',
  PASTEL_PURPLE_FOCUS: '#D8B9D8',
  PASTEL_PINK_FOCUS: '#FFDEE7',
  PASTEL_BROWN_FOCUS: '#ECD8BA',
  PASTEL_GRAY_FOCUS: '#EBEBEB',
  PASTEL_WHITE_FOCUS: '#FFFFFF',

  // === GRADIENTS ===
  PASTEL_RED_GRADIENT: 'linear-gradient(135deg, #FFEAEA, #F28B82)',
  PASTEL_ORANGE_GRADIENT: 'linear-gradient(135deg, #FFF4E6, #FBCB8B)',
  PASTEL_YELLOW_GRADIENT: 'linear-gradient(135deg, #FFFDEA, #FFF2A1)',
  PASTEL_GREEN_GRADIENT: 'linear-gradient(135deg, #EAFBF6, #B5EAD7)',
  PASTEL_BLUE_GRADIENT: 'linear-gradient(135deg, #EAF1FA, #A7C7E7)',
  PASTEL_PURPLE_GRADIENT: 'linear-gradient(135deg, #F5EAF5, #CBAACB)',
  PASTEL_PINK_GRADIENT: 'linear-gradient(135deg, #FFF0F4, #FFD1DC)',
  PASTEL_BROWN_GRADIENT: 'linear-gradient(135deg, #FAF5EE, #E6CBA8)',
  PASTEL_GRAY_GRADIENT: 'linear-gradient(135deg, #F8F8F8, #E0E0E0)',
  PASTEL__WHITE_GRADIENT: 'linear-gradient(135deg, #FFFFFF, #FAFAFA)',

  BLACK: '#000000',
  WHITE: '#FFFFFF',
};


export const ColorPalette = {
  primary: {
    light: COLORS.PASTEL_BLUE_FOCUS,
    main: COLORS.PASTEL_BLUE,
    dark: COLORS.PASTEL_BLUE_HOVER,
    contrastText: COLORS.BLACK,
  },
  secondary: {
    light: COLORS.PASTEL_ORANGE_FOCUS,
    main: COLORS.PASTEL_ORANGE,
    dark: COLORS.PASTEL_ORANGE_HOVER,
    contrastText: COLORS.BLACK,
  },
  error: {
    light: COLORS.PASTEL_RED_FOCUS,
    main: COLORS.PASTEL_RED,
    dark: COLORS.PASTEL_RED_HOVER,
    contrastText: COLORS.BLACK,
  },
  success: {
    light: COLORS.PASTEL_GREEN_FOCUS,
    main: COLORS.PASTEL_GREEN,
    dark: COLORS.PASTEL_GREEN_HOVER,
    contrastText: COLORS.BLACK,
  },
  warning: {
    light: COLORS.PASTEL_YELLOW_FOCUS,
    main: COLORS.PASTEL_YELLOW,
    dark: COLORS.PASTEL_YELLOW_HOVER,
    contrastText: COLORS.BLACK,
  },

  grey: {
    50: '#FAFAFA',
    100: '#F5F5F5',
    200: '#EEEEEE',
    300: '#E0E0E0',
    400: '#C7C7C7',
    500: '#9E9E9E',
    600: '#757575',
    700: '#616161',
    800: '#424242',
    900: '#212121',
  },

  white: COLORS.WHITE,

  background: {
    default: COLORS.PASTEL_WHITE,
    paper: COLORS.WHITE,
  },

  text: {
    primary: COLORS.BLACK,
    secondary: '#616161',
    disabled: '#9E9E9E',
  },

  divider: '#E0E0E0',

  // === CUSTOM ===
  pastel: {
    red: COLORS.PASTEL_RED,
    orange: COLORS.PASTEL_ORANGE,
    yellow: COLORS.PASTEL_YELLOW,
    green: COLORS.PASTEL_GREEN,
    blue: COLORS.PASTEL_BLUE,
    purple: COLORS.PASTEL_PURPLE,
    pink: COLORS.PASTEL_PINK,
    brown: COLORS.PASTEL_BROWN,
    gray: COLORS.PASTEL_GRAY,
    white: COLORS.PASTEL_WHITE,
  },

  pastel_hover: {
    red: COLORS.PASTEL_RED_HOVER,
    orange: COLORS.PASTEL_ORANGE_HOVER,
    yellow: COLORS.PASTEL_YELLOW_HOVER,
    green: COLORS.PASTEL_GREEN_HOVER,
    blue: COLORS.PASTEL_BLUE_HOVER,
    purple: COLORS.PASTEL_PURPLE_HOVER,
    pink: COLORS.PASTEL_PINK_HOVER,
    brown: COLORS.PASTEL_BROWN_HOVER,
    gray: COLORS.PASTEL_GRAY_HOVER,
    white: COLORS.PASTEL_WHITE_HOVER,
  },

  gradients: {
    red: COLORS.PASTEL_RED_GRADIENT,
    orange: COLORS.PASTEL_ORANGE_GRADIENT,
    yellow: COLORS.PASTEL_YELLOW_GRADIENT,
    green: COLORS.PASTEL_GREEN_GRADIENT,
    blue: COLORS.PASTEL_BLUE_GRADIENT,
    purple: COLORS.PASTEL_PURPLE_GRADIENT,
    pink: COLORS.PASTEL_PINK_GRADIENT,
    brown: COLORS.PASTEL_BROWN_GRADIENT,
    gray: COLORS.PASTEL_GRAY_GRADIENT,
    white: COLORS.PASTEL__WHITE_GRADIENT,
  },
};